// src-tauri/src/database/migrations/load.rs
// Loaders for bundled drizzle + manual migrations.

use super::MigrationJournal;
use crate::database::error::DatabaseError;
use tauri::{path::BaseDirectory, Manager};
use tauri_plugin_fs::FsExt;

/// Reads the migration journal to get the list of all migration file names
fn load_migration_journal(app_handle: &tauri::AppHandle) -> Result<Vec<String>, DatabaseError> {
    let fs = app_handle.fs();

    let journal_path = app_handle
        .path()
        .resolve(
            "database/migrations/meta/_journal.json",
            BaseDirectory::Resource,
        )
        .map_err(|e| DatabaseError::MigrationError {
            reason: format!("Failed to resolve journal path: {}", e),
        })?;

    println!(
        "[MIGRATIONS] load_migration_journal: reading from {:?}",
        journal_path
    );

    let content = fs
        .read_to_string(&journal_path)
        .map_err(|e| DatabaseError::MigrationError {
            reason: format!("Failed to read migration journal: {}", e),
        })?;

    let journal: MigrationJournal =
        serde_json::from_str(&content).map_err(|e| DatabaseError::MigrationError {
            reason: format!("Failed to parse migration journal: {}", e),
        })?;

    // Sort by idx and extract tags
    let mut entries = journal.entries;
    entries.sort_by_key(|e| e.idx);
    let migration_names: Vec<String> = entries.into_iter().map(|e| e.tag).collect();

    println!(
        "[MIGRATIONS] load_migration_journal: found {} migrations",
        migration_names.len()
    );

    Ok(migration_names)
}

/// Loads all migration files from the bundled resources directory
///
/// Uses FsExt to read files, which works on all platforms including Android
/// where resources are stored in the APK as assets.
/// Reads the migration list from meta/_journal.json (generated by drizzle-kit),
/// then appends the hand-maintained manual migrations (e.g. SQLite triggers
/// that drizzle-kit cannot model) from the separate `migrations-manual` folder.
///
/// Ordering is significant: drizzle migrations first (journal order), manual
/// migrations second (manual journal order). By naming convention, manual tags
/// carry a `manual_` prefix so they never collide with drizzle tags in the
/// by-name applied tracking. Nothing in this function enforces the prefix; the
/// convention is guarded at test time by the manual-journal sync test.
pub(super) fn load_bundled_migrations(
    app_handle: &tauri::AppHandle,
) -> Result<Vec<(String, String)>, DatabaseError> {
    // Read migration names from journal
    let migration_names = load_migration_journal(app_handle)?;

    println!(
        "[MIGRATIONS] load_bundled_migrations: loading {} drizzle migrations via FsExt",
        migration_names.len()
    );

    let fs = app_handle.fs();
    let mut migrations = Vec::new();

    for migration_name in &migration_names {
        let relative_path = format!("database/migrations/{}.sql", migration_name);

        let resource_path = app_handle
            .path()
            .resolve(&relative_path, BaseDirectory::Resource)
            .map_err(|e| DatabaseError::MigrationError {
                reason: format!(
                    "Failed to resolve migration path '{}': {}",
                    relative_path, e
                ),
            })?;

        println!(
            "[MIGRATIONS] load_bundled_migrations: reading '{}' from {:?}",
            migration_name, resource_path
        );

        let content =
            fs.read_to_string(&resource_path)
                .map_err(|e| DatabaseError::MigrationError {
                    reason: format!("Failed to read migration file '{}': {}", migration_name, e),
                })?;

        migrations.push((migration_name.to_string(), content));
    }

    // Append manual migrations after the drizzle baseline.
    let manual = load_manual_migrations(app_handle)?;
    migrations.extend(manual);

    println!(
        "[MIGRATIONS] 📂 Loaded {} migration files: {:?}",
        migrations.len(),
        migrations.iter().map(|(n, _)| n).collect::<Vec<_>>()
    );
    Ok(migrations)
}

/// Reads the manual-migrations journal (migrations-manual/_journal.json).
///
/// Unlike the drizzle journal this one is hand-maintained at dev time. It is
/// optional: if the journal is absent (or has no entries) this returns an
/// empty list rather than failing, so the runner degrades gracefully when no
/// manual migrations exist.
fn load_manual_migration_journal(
    app_handle: &tauri::AppHandle,
) -> Result<Vec<String>, DatabaseError> {
    let fs = app_handle.fs();

    let journal_path = app_handle
        .path()
        .resolve(
            "database/migrations-manual/_journal.json",
            BaseDirectory::Resource,
        )
        .map_err(|e| DatabaseError::MigrationError {
            reason: format!("Failed to resolve manual journal path: {}", e),
        })?;

    println!(
        "[MIGRATIONS] load_manual_migration_journal: reading from {:?}",
        journal_path
    );

    // An absent journal is fine — no manual migrations to apply. Any other read
    // failure (corruption, permissions, a broken bundle) must NOT be silently
    // swallowed: that would skip the manual migrations and leave the DB missing
    // their effects (e.g. replication triggers).
    let content = match fs.read_to_string(&journal_path) {
        Ok(content) => content,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            println!("[MIGRATIONS] load_manual_migration_journal: no manual journal, skipping");
            return Ok(Vec::new());
        }
        Err(e) => {
            return Err(DatabaseError::MigrationError {
                reason: format!("Failed to read manual migration journal: {}", e),
            });
        }
    };

    let journal: MigrationJournal =
        serde_json::from_str(&content).map_err(|e| DatabaseError::MigrationError {
            reason: format!("Failed to parse manual migration journal: {}", e),
        })?;

    // Sort by idx and extract tags
    let mut entries = journal.entries;
    entries.sort_by_key(|e| e.idx);
    let migration_names: Vec<String> = entries.into_iter().map(|e| e.tag).collect();

    println!(
        "[MIGRATIONS] load_manual_migration_journal: found {} manual migrations",
        migration_names.len()
    );

    Ok(migration_names)
}

/// Loads the hand-maintained manual migrations (e.g. SQLite triggers drizzle
/// cannot model) from the `migrations-manual` folder, in manual-journal order.
///
/// Reads each `database/migrations-manual/<tag>.sql` BY PATH (never directory
/// listing — APK assets can't be reliably enumerated at runtime on Android),
/// exactly like the drizzle loader. Returns an empty list when no manual
/// journal/entries exist.
fn load_manual_migrations(
    app_handle: &tauri::AppHandle,
) -> Result<Vec<(String, String)>, DatabaseError> {
    let migration_names = load_manual_migration_journal(app_handle)?;

    if migration_names.is_empty() {
        return Ok(Vec::new());
    }

    println!(
        "[MIGRATIONS] load_manual_migrations: loading {} manual migrations via FsExt",
        migration_names.len()
    );

    let fs = app_handle.fs();
    let mut migrations = Vec::new();

    for migration_name in &migration_names {
        let relative_path = format!("database/migrations-manual/{}.sql", migration_name);

        let resource_path = app_handle
            .path()
            .resolve(&relative_path, BaseDirectory::Resource)
            .map_err(|e| DatabaseError::MigrationError {
                reason: format!(
                    "Failed to resolve manual migration path '{}': {}",
                    relative_path, e
                ),
            })?;

        println!(
            "[MIGRATIONS] load_manual_migrations: reading '{}' from {:?}",
            migration_name, resource_path
        );

        let content =
            fs.read_to_string(&resource_path)
                .map_err(|e| DatabaseError::MigrationError {
                    reason: format!(
                        "Failed to read manual migration file '{}': {}",
                        migration_name, e
                    ),
                })?;

        migrations.push((migration_name.to_string(), content));
    }

    Ok(migrations)
}
