// src-tauri/src/extension/filesync/queries.rs
//!
//! SQL queries for FileSync operations
//!
//! Uses CRDT-compatible execution via the core database functions.
//! All SQL operations automatically handle tombstone filtering.

use crate::table_names::{
    // File backends table
    COL_FILE_BACKENDS_CREATED_AT, COL_FILE_BACKENDS_ENABLED, COL_FILE_BACKENDS_ENCRYPTED_CONFIG,
    COL_FILE_BACKENDS_ID, COL_FILE_BACKENDS_NAME, COL_FILE_BACKENDS_TYPE, TABLE_FILE_BACKENDS,
    // Files table
    COL_FILES_CHUNK_COUNT, COL_FILES_CONTENT_HASH, COL_FILES_CREATED_AT,
    COL_FILES_ENCRYPTED_MIME_TYPE, COL_FILES_ENCRYPTED_NAME, COL_FILES_ENCRYPTED_PATH,
    COL_FILES_ID, COL_FILES_IS_DIRECTORY, COL_FILES_PARENT_ID, COL_FILES_SIZE, COL_FILES_SPACE_ID,
    COL_FILES_SYNC_STATE, COL_FILES_UPDATED_AT, COL_FILES_WRAPPED_KEY, TABLE_FILES,
    // File spaces table
    COL_FILE_SPACES_CREATED_AT, COL_FILE_SPACES_FILE_COUNT, COL_FILE_SPACES_ID,
    COL_FILE_SPACES_IS_PERSONAL, COL_FILE_SPACES_NAME, COL_FILE_SPACES_TOTAL_SIZE,
    COL_FILE_SPACES_UPDATED_AT, COL_FILE_SPACES_WRAPPED_KEY, TABLE_FILE_SPACES,
    // File backend mapping table
    COL_FILE_BACKEND_MAPPING_BACKEND_ID, COL_FILE_BACKEND_MAPPING_FILE_ID,
    COL_FILE_BACKEND_MAPPING_ID, COL_FILE_BACKEND_MAPPING_REMOTE_ID,
    COL_FILE_BACKEND_MAPPING_UPLOADED_AT, TABLE_FILE_BACKEND_MAPPING,
    // Sync rules tables
    COL_FILE_SYNC_RULES_CREATED_AT, COL_FILE_SYNC_RULES_DIRECTION, COL_FILE_SYNC_RULES_ENABLED,
    COL_FILE_SYNC_RULES_ID, COL_FILE_SYNC_RULES_LOCAL_PATH, COL_FILE_SYNC_RULES_SPACE_ID,
    COL_FILE_SYNC_RULES_UPDATED_AT, TABLE_FILE_SYNC_RULES,
    COL_FILE_SYNC_RULE_BACKENDS_BACKEND_ID, COL_FILE_SYNC_RULE_BACKENDS_ID,
    COL_FILE_SYNC_RULE_BACKENDS_RULE_ID, TABLE_FILE_SYNC_RULE_BACKENDS,
};

lazy_static::lazy_static! {
    // ============================================================================
    // File Spaces Queries
    // ============================================================================

    pub static ref SQL_LIST_SPACES: String = format!(
        "SELECT {COL_FILE_SPACES_ID}, {COL_FILE_SPACES_NAME}, {COL_FILE_SPACES_IS_PERSONAL}, \
         {COL_FILE_SPACES_FILE_COUNT}, {COL_FILE_SPACES_TOTAL_SIZE}, {COL_FILE_SPACES_CREATED_AT}, \
         {COL_FILE_SPACES_UPDATED_AT} \
         FROM {TABLE_FILE_SPACES} ORDER BY {COL_FILE_SPACES_NAME}"
    );

    pub static ref SQL_INSERT_SPACE: String = format!(
        "INSERT INTO {TABLE_FILE_SPACES} ({COL_FILE_SPACES_ID}, {COL_FILE_SPACES_NAME}, \
         {COL_FILE_SPACES_WRAPPED_KEY}, {COL_FILE_SPACES_IS_PERSONAL}, {COL_FILE_SPACES_FILE_COUNT}, \
         {COL_FILE_SPACES_TOTAL_SIZE}) \
         VALUES (?1, ?2, ?3, 1, 0, 0) \
         RETURNING {COL_FILE_SPACES_ID}, {COL_FILE_SPACES_NAME}, {COL_FILE_SPACES_IS_PERSONAL}, \
         {COL_FILE_SPACES_FILE_COUNT}, {COL_FILE_SPACES_TOTAL_SIZE}, {COL_FILE_SPACES_CREATED_AT}, \
         {COL_FILE_SPACES_UPDATED_AT}"
    );

    pub static ref SQL_DELETE_SPACE: String = format!(
        "DELETE FROM {TABLE_FILE_SPACES} WHERE {COL_FILE_SPACES_ID} = ?1"
    );

    pub static ref SQL_UPDATE_SPACE_COUNTS: String = format!(
        "UPDATE {TABLE_FILE_SPACES} \
         SET {COL_FILE_SPACES_FILE_COUNT} = {COL_FILE_SPACES_FILE_COUNT} + ?1, \
         {COL_FILE_SPACES_TOTAL_SIZE} = {COL_FILE_SPACES_TOTAL_SIZE} + ?2 \
         WHERE {COL_FILE_SPACES_ID} = ?3"
    );

    // ============================================================================
    // File Backends Queries
    // ============================================================================

    pub static ref SQL_LIST_BACKENDS: String = format!(
        "SELECT {COL_FILE_BACKENDS_ID}, {COL_FILE_BACKENDS_TYPE}, {COL_FILE_BACKENDS_NAME}, \
         {COL_FILE_BACKENDS_ENABLED}, {COL_FILE_BACKENDS_CREATED_AT} \
         FROM {TABLE_FILE_BACKENDS} ORDER BY {COL_FILE_BACKENDS_NAME}"
    );

    pub static ref SQL_GET_BACKEND_CONFIG: String = format!(
        "SELECT {COL_FILE_BACKENDS_ENCRYPTED_CONFIG} FROM {TABLE_FILE_BACKENDS} \
         WHERE {COL_FILE_BACKENDS_ID} = ?1"
    );

    pub static ref SQL_GET_BACKEND: String = format!(
        "SELECT {COL_FILE_BACKENDS_TYPE}, {COL_FILE_BACKENDS_ENCRYPTED_CONFIG} \
         FROM {TABLE_FILE_BACKENDS} WHERE {COL_FILE_BACKENDS_ID} = ?1"
    );

    pub static ref SQL_INSERT_BACKEND: String = format!(
        "INSERT INTO {TABLE_FILE_BACKENDS} ({COL_FILE_BACKENDS_ID}, {COL_FILE_BACKENDS_TYPE}, \
         {COL_FILE_BACKENDS_NAME}, {COL_FILE_BACKENDS_ENCRYPTED_CONFIG}, {COL_FILE_BACKENDS_ENABLED}) \
         VALUES (?1, ?2, ?3, ?4, 1) \
         RETURNING {COL_FILE_BACKENDS_ID}, {COL_FILE_BACKENDS_TYPE}, {COL_FILE_BACKENDS_NAME}, \
         {COL_FILE_BACKENDS_ENABLED}, {COL_FILE_BACKENDS_CREATED_AT}"
    );

    pub static ref SQL_DELETE_BACKEND: String = format!(
        "DELETE FROM {TABLE_FILE_BACKENDS} WHERE {COL_FILE_BACKENDS_ID} = ?1"
    );

    pub static ref SQL_LIST_ENABLED_BACKENDS: String = format!(
        "SELECT {COL_FILE_BACKENDS_ID} FROM {TABLE_FILE_BACKENDS} WHERE {COL_FILE_BACKENDS_ENABLED} = 1"
    );

    // ============================================================================
    // Files Queries
    // ============================================================================

    pub static ref SQL_INSERT_FILE: String = format!(
        "INSERT INTO {TABLE_FILES} ({COL_FILES_ID}, {COL_FILES_SPACE_ID}, {COL_FILES_ENCRYPTED_NAME}, \
         {COL_FILES_ENCRYPTED_PATH}, {COL_FILES_ENCRYPTED_MIME_TYPE}, {COL_FILES_IS_DIRECTORY}, \
         {COL_FILES_SIZE}, {COL_FILES_CONTENT_HASH}, {COL_FILES_WRAPPED_KEY}, {COL_FILES_CHUNK_COUNT}, \
         {COL_FILES_SYNC_STATE}) \
         VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)"
    );

    pub static ref SQL_LIST_FILES: String = format!(
        "SELECT {COL_FILES_ID}, {COL_FILES_SPACE_ID}, {COL_FILES_ENCRYPTED_NAME}, {COL_FILES_ENCRYPTED_PATH}, \
         {COL_FILES_ENCRYPTED_MIME_TYPE}, {COL_FILES_IS_DIRECTORY}, {COL_FILES_SIZE}, {COL_FILES_CONTENT_HASH}, \
         {COL_FILES_SYNC_STATE}, {COL_FILES_CREATED_AT}, {COL_FILES_UPDATED_AT} \
         FROM {TABLE_FILES} WHERE {COL_FILES_SPACE_ID} = ?1 ORDER BY {COL_FILES_IS_DIRECTORY} DESC, {COL_FILES_ENCRYPTED_NAME}"
    );

    pub static ref SQL_LIST_FILES_IN_FOLDER: String = format!(
        "SELECT {COL_FILES_ID}, {COL_FILES_SPACE_ID}, {COL_FILES_ENCRYPTED_NAME}, {COL_FILES_ENCRYPTED_PATH}, \
         {COL_FILES_ENCRYPTED_MIME_TYPE}, {COL_FILES_IS_DIRECTORY}, {COL_FILES_SIZE}, {COL_FILES_CONTENT_HASH}, \
         {COL_FILES_SYNC_STATE}, {COL_FILES_CREATED_AT}, {COL_FILES_UPDATED_AT} \
         FROM {TABLE_FILES} WHERE {COL_FILES_SPACE_ID} = ?1 AND {COL_FILES_PARENT_ID} = ?2 \
         ORDER BY {COL_FILES_IS_DIRECTORY} DESC, {COL_FILES_ENCRYPTED_NAME}"
    );

    pub static ref SQL_LIST_FILES_ROOT: String = format!(
        "SELECT {COL_FILES_ID}, {COL_FILES_SPACE_ID}, {COL_FILES_ENCRYPTED_NAME}, {COL_FILES_ENCRYPTED_PATH}, \
         {COL_FILES_ENCRYPTED_MIME_TYPE}, {COL_FILES_IS_DIRECTORY}, {COL_FILES_SIZE}, {COL_FILES_CONTENT_HASH}, \
         {COL_FILES_SYNC_STATE}, {COL_FILES_CREATED_AT}, {COL_FILES_UPDATED_AT} \
         FROM {TABLE_FILES} WHERE {COL_FILES_SPACE_ID} = ?1 AND {COL_FILES_PARENT_ID} IS NULL \
         ORDER BY {COL_FILES_IS_DIRECTORY} DESC, {COL_FILES_ENCRYPTED_NAME}"
    );

    pub static ref SQL_GET_FILE: String = format!(
        "SELECT {COL_FILES_ID}, {COL_FILES_SPACE_ID}, {COL_FILES_ENCRYPTED_NAME}, {COL_FILES_ENCRYPTED_PATH}, \
         {COL_FILES_ENCRYPTED_MIME_TYPE}, {COL_FILES_IS_DIRECTORY}, {COL_FILES_SIZE}, {COL_FILES_CONTENT_HASH}, \
         {COL_FILES_WRAPPED_KEY}, {COL_FILES_SYNC_STATE}, {COL_FILES_CREATED_AT}, {COL_FILES_UPDATED_AT} \
         FROM {TABLE_FILES} WHERE {COL_FILES_ID} = ?1"
    );

    pub static ref SQL_DELETE_FILE: String = format!(
        "DELETE FROM {TABLE_FILES} WHERE {COL_FILES_ID} = ?1"
    );

    // ============================================================================
    // File Backend Mapping Queries
    // ============================================================================

    pub static ref SQL_INSERT_BACKEND_MAPPING: String = format!(
        "INSERT INTO {TABLE_FILE_BACKEND_MAPPING} ({COL_FILE_BACKEND_MAPPING_ID}, \
         {COL_FILE_BACKEND_MAPPING_FILE_ID}, {COL_FILE_BACKEND_MAPPING_BACKEND_ID}, \
         {COL_FILE_BACKEND_MAPPING_REMOTE_ID}, {COL_FILE_BACKEND_MAPPING_UPLOADED_AT}) \
         VALUES (?1, ?2, ?3, ?4, datetime('now'))"
    );

    pub static ref SQL_GET_FILE_BACKENDS: String = format!(
        "SELECT {COL_FILE_BACKEND_MAPPING_BACKEND_ID} FROM {TABLE_FILE_BACKEND_MAPPING} \
         WHERE {COL_FILE_BACKEND_MAPPING_FILE_ID} = ?1"
    );

    pub static ref SQL_GET_FILE_REMOTE_ID: String = format!(
        "SELECT {COL_FILE_BACKEND_MAPPING_REMOTE_ID} FROM {TABLE_FILE_BACKEND_MAPPING} \
         WHERE {COL_FILE_BACKEND_MAPPING_FILE_ID} = ?1 AND {COL_FILE_BACKEND_MAPPING_BACKEND_ID} = ?2"
    );

    // ============================================================================
    // Sync Rules Queries
    // ============================================================================

    pub static ref SQL_LIST_SYNC_RULES: String = format!(
        "SELECT {COL_FILE_SYNC_RULES_ID}, {COL_FILE_SYNC_RULES_SPACE_ID}, {COL_FILE_SYNC_RULES_LOCAL_PATH}, \
         {COL_FILE_SYNC_RULES_DIRECTION}, {COL_FILE_SYNC_RULES_ENABLED}, {COL_FILE_SYNC_RULES_CREATED_AT}, \
         {COL_FILE_SYNC_RULES_UPDATED_AT} \
         FROM {TABLE_FILE_SYNC_RULES} ORDER BY {COL_FILE_SYNC_RULES_LOCAL_PATH}"
    );

    pub static ref SQL_INSERT_SYNC_RULE: String = format!(
        "INSERT INTO {TABLE_FILE_SYNC_RULES} ({COL_FILE_SYNC_RULES_ID}, {COL_FILE_SYNC_RULES_SPACE_ID}, \
         {COL_FILE_SYNC_RULES_LOCAL_PATH}, {COL_FILE_SYNC_RULES_DIRECTION}, {COL_FILE_SYNC_RULES_ENABLED}) \
         VALUES (?1, ?2, ?3, ?4, 1) \
         RETURNING {COL_FILE_SYNC_RULES_ID}, {COL_FILE_SYNC_RULES_SPACE_ID}, {COL_FILE_SYNC_RULES_LOCAL_PATH}, \
         {COL_FILE_SYNC_RULES_DIRECTION}, {COL_FILE_SYNC_RULES_ENABLED}, {COL_FILE_SYNC_RULES_CREATED_AT}, \
         {COL_FILE_SYNC_RULES_UPDATED_AT}"
    );

    pub static ref SQL_DELETE_SYNC_RULE: String = format!(
        "DELETE FROM {TABLE_FILE_SYNC_RULES} WHERE {COL_FILE_SYNC_RULES_ID} = ?1"
    );

    pub static ref SQL_GET_SYNC_RULE: String = format!(
        "SELECT {COL_FILE_SYNC_RULES_ID}, {COL_FILE_SYNC_RULES_SPACE_ID}, {COL_FILE_SYNC_RULES_LOCAL_PATH}, \
         {COL_FILE_SYNC_RULES_DIRECTION}, {COL_FILE_SYNC_RULES_ENABLED}, {COL_FILE_SYNC_RULES_CREATED_AT}, \
         {COL_FILE_SYNC_RULES_UPDATED_AT} \
         FROM {TABLE_FILE_SYNC_RULES} WHERE {COL_FILE_SYNC_RULES_ID} = ?1"
    );

    pub static ref SQL_GET_SYNC_RULE_BY_SPACE: String = format!(
        "SELECT {COL_FILE_SYNC_RULES_ID}, {COL_FILE_SYNC_RULES_SPACE_ID}, {COL_FILE_SYNC_RULES_LOCAL_PATH}, \
         {COL_FILE_SYNC_RULES_DIRECTION}, {COL_FILE_SYNC_RULES_ENABLED}, {COL_FILE_SYNC_RULES_CREATED_AT}, \
         {COL_FILE_SYNC_RULES_UPDATED_AT} \
         FROM {TABLE_FILE_SYNC_RULES} WHERE {COL_FILE_SYNC_RULES_SPACE_ID} = ?1 LIMIT 1"
    );

    pub static ref SQL_UPDATE_SYNC_RULE_DIRECTION: String = format!(
        "UPDATE {TABLE_FILE_SYNC_RULES} SET {COL_FILE_SYNC_RULES_DIRECTION} = ?1 \
         WHERE {COL_FILE_SYNC_RULES_ID} = ?2"
    );

    pub static ref SQL_UPDATE_SYNC_RULE_ENABLED: String = format!(
        "UPDATE {TABLE_FILE_SYNC_RULES} SET {COL_FILE_SYNC_RULES_ENABLED} = ?1 \
         WHERE {COL_FILE_SYNC_RULES_ID} = ?2"
    );

    pub static ref SQL_GET_RULE_BACKENDS: String = format!(
        "SELECT {COL_FILE_SYNC_RULE_BACKENDS_BACKEND_ID} FROM {TABLE_FILE_SYNC_RULE_BACKENDS} \
         WHERE {COL_FILE_SYNC_RULE_BACKENDS_RULE_ID} = ?1"
    );

    pub static ref SQL_INSERT_RULE_BACKEND: String = format!(
        "INSERT INTO {TABLE_FILE_SYNC_RULE_BACKENDS} ({COL_FILE_SYNC_RULE_BACKENDS_ID}, \
         {COL_FILE_SYNC_RULE_BACKENDS_RULE_ID}, {COL_FILE_SYNC_RULE_BACKENDS_BACKEND_ID}) \
         VALUES (?1, ?2, ?3)"
    );

    pub static ref SQL_DELETE_RULE_BACKENDS: String = format!(
        "DELETE FROM {TABLE_FILE_SYNC_RULE_BACKENDS} WHERE {COL_FILE_SYNC_RULE_BACKENDS_RULE_ID} = ?1"
    );
}
