// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImapConfig } from "./ImapConfig";
import type { SmtpConfig } from "./SmtpConfig";

/**
 * A mail account: IMAP for fetch, SMTP for send.
 *
 * SMTP is optional so an account can be fetch-only.
 */
export type Account = { 
/**
 * Caller-defined identifier. Used by future connection-pool keying;
 * must be stable per logical account.
 */
id: string, imap: ImapConfig, smtp: SmtpConfig | null, };
