// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookmarksAction } from "./BookmarksAction";
import type { DbAction } from "./DbAction";
import type { ExtensionApiAction } from "./ExtensionApiAction";
import type { FsAction } from "./FsAction";
import type { IdentityAction } from "./IdentityAction";
import type { MailAction } from "./MailAction";
import type { NotificationsAction } from "./NotificationsAction";
import type { PasswordsAction } from "./PasswordsAction";
import type { RwAction } from "./RwAction";
import type { ShellAction } from "./ShellAction";
import type { SpaceAction } from "./SpaceAction";
import type { WebAction } from "./WebAction";

/**
 * Ein typsicherer Container, der die spezifische Aktion für einen Ressourcentyp enthält.
 */
export type Action = { "Database": DbAction } | { "Filesystem": FsAction } | { "Web": WebAction } | { "Shell": ShellAction } | { "SyncServers": RwAction } | { "CloudStorage": RwAction } | { "SyncRules": RwAction } | { "Spaces": SpaceAction } | { "Identities": IdentityAction } | { "Passwords": PasswordsAction } | { "Bookmarks": BookmarksAction } | { "Mail": MailAction } | { "Notifications": NotificationsAction } | { "ExtensionApi": ExtensionApiAction };
