// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackendConfig } from "./BackendConfig";

export type AddBackendRequest = { name: string, config: BackendConfig, };
