// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3BackendConfig } from "./S3BackendConfig";
import type { StorageBackendType } from "./StorageBackendType";

export type AddBackendRequest = { type: StorageBackendType, name: string, config: S3BackendConfig, };
