// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Email address, optionally with display name.
 */
export type Address = { name: string | null, email: string, };
