// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to add a new storage backend
 */
export type AddStorageBackendRequest = { 
/**
 * Display name for the backend
 */
name: string, 
/**
 * Backend type (currently only "s3")
 */
type: string, 
/**
 * Configuration (structure depends on type) - JSON string that will be parsed
 */
config: Record<string, unknown>, };
