// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictStrategy } from "./ConflictStrategy";
import type { SyncDirection } from "./SyncDirection";

export type AddSyncRuleRequest = { spaceId: string, localPath: string, backendIds: Array<string>, direction: SyncDirection | null, 
/**
 * Gitignore-like patterns for files/folders to exclude from sync
 */
ignorePatterns: Array<string> | null, 
/**
 * Default conflict resolution strategy (defaults to Ask)
 */
conflictStrategy: ConflictStrategy | null, };
