// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncDirection } from "./SyncDirection";

export type AddSyncRuleRequest = { spaceId: string, localPath: string, backendIds: Array<string>, direction: SyncDirection | null, };
