// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueFileEntry } from "./QueueFileEntry";
import type { QueueOperation } from "./QueueOperation";

/**
 * Request to add files to the sync queue
 */
export type AddToQueueRequest = { 
/**
 * Sync rule ID
 */
ruleId: string, 
/**
 * Files to add (local paths relative to sync root)
 */
files: Array<QueueFileEntry>, 
/**
 * Operation type
 */
operation: QueueOperation, 
/**
 * Priority (optional, default 100)
 */
priority: number | null, };
