// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attachment metadata returned in `Message.attachments`. Body data is
 * fetched separately to keep list/read responses lean.
 */
export type Attachment = { 
/**
 * Index of this part in the parsed message (callers use it to
 * request the data on demand).
 */
partIndex: number, filename: string | null, contentType: string, size: bigint, 
/**
 * Content-ID for inline images referenced by HTML body.
 */
contentId: string | null, isInline: boolean, };
