// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An authorized client stored in the database
 */
export type AuthorizedClient = { 
/**
 * Row ID
 */
id: string, 
/**
 * Unique client identifier (public key fingerprint)
 */
clientId: string, 
/**
 * Human-readable client name
 */
clientName: string, 
/**
 * Client's public key (base64)
 */
publicKey: string, 
/**
 * Extension ID this client can access
 */
extensionId: string, 
/**
 * When the client was authorized (ISO 8601)
 */
authorizedAt: string | null, 
/**
 * Last time the client connected (ISO 8601)
 */
lastSeen: string | null, 
/**
 * Canonical JSON of the client's declared manifest at authorization time
 * (`ClientInfo.permissions` + `requestedExtensions[].actions`). Compared
 * against the live handshake declaration to detect manifest changes.
 */
requestedPermissions: string, };
