// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3BackendConfig } from "./S3BackendConfig";

/**
 * Backend configuration for S3-compatible storage
 */
export type BackendConfig = { "type": "s3" } & S3BackendConfig | { "type": "r2" } & S3BackendConfig | { "type": "minio" } & S3BackendConfig;
