// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A blocked client stored in the database
 */
export type BlockedClient = { 
/**
 * Row ID
 */
id: string, 
/**
 * Unique client identifier (public key fingerprint)
 */
clientId: string, 
/**
 * Human-readable client name
 */
clientName: string, 
/**
 * Client's public key (base64)
 */
publicKey: string, 
/**
 * When the client was blocked (ISO 8601)
 */
blockedAt: string | null, };
