// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Bookmarks-Permission ist nicht Tag-/Sammlungs-granular: `Read`/`ReadWrite`
 * gilt für alle Sammlungen (`haex_bookmark_collections`) gleichermaßen.
 */
export type BookmarksAction = "read" | "readWrite";
