// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-chunk + whole-file BLAKE3 hashes for resumable downloads.
 *
 * Travels on the wire: served by the peer_storage stat-probe so file-browser
 * downloads can verify chunks without the receiver knowing the hashes in
 * advance, and carried in `FileState` so sync-rule manifests authoritatively
 * pin the expected hashes per chunk.
 */
export type ChunkedHash = { 
/**
 * BLAKE3 of the full file, lowercase hex.
 */
fileHash: string, 
/**
 * Bytes per chunk (the last chunk may be shorter).
 */
chunkSize: number, 
/**
 * BLAKE3 of each chunk, lowercase hex, in order.
 */
chunkHashes: Array<string>, };
