// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of claiming a local invite.
 */
export type ClaimInviteResult = { spaceId: string, capability: string, };
