// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of tombstone cleanup operation
 */
export type CleanupResult = { 
/**
 * Number of tombstone entries hard-deleted across all tables
 */
tombstonesDeleted: number, 
/**
 * Number of tables processed (kept for backwards compatibility)
 */
appliedDeleted: number, 
/**
 * Total entries deleted
 */
totalDeleted: number, };
