// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the delete-log cleanup operation. Vault-side aggregate: the
 * `rows_deleted` count sums the crate's owner-domain prune of
 * `haex_deleted_rows` with the vault-owned prune of
 * `haex_shared_space_deleted_rows` so the frontend reports the total across
 * both logs. Shape mirrors `haex_crdt::CleanupResult` (the crate's type does
 * not derive `ts-rs::TS`, so we redeclare it here to keep the binding
 * auto-generated).
 */
export type CleanupResult = { 
/**
 * Total rows removed from the delete-log across `haex_deleted_rows`
 * (owner domain) and `haex_shared_space_deleted_rows` (per-space).
 */
rowsDeleted: number, 
/**
 * Max HLC of the entries that were pruned from `haex_deleted_rows`
 * (the crate's owner-domain prune). `None` when that pass was a no-op.
 */
maxPrunedHlc: string | null, };
