// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of tombstone cleanup operation
 */
export type CleanupResult = { 
/**
 * Number of tombstone entries deleted
 */
tombstones_deleted: number, 
/**
 * Number of applied entries deleted (non-DELETE operations)
 */
applied_deleted: number, 
/**
 * Total entries deleted
 */
total_deleted: number, };
