// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionPermissions } from "./ExtensionPermissions";

/**
 * Declared core (haex-vault built-in) permissions a client wants at
 * handshake time. Reuses the extension manifest's `ExtensionPermissions`
 * shape — today only `passwords` is relevant for external clients.
 */
export type ClientPermissions = { core: ExtensionPermissions, };
