// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Information about a connected client
 */
export type ClientInfo = { 
/**
 * Unique client identifier (public key fingerprint)
 */
clientId: string, 
/**
 * Human-readable client name (e.g., "haex-pass Browser Extension")
 */
clientName: string, 
/**
 * Client's public key for encryption (base64)
 */
publicKey: string, };
