// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conflict resolution strategy for sync rules
 */
export type ConflictStrategy = "local" | "remote" | "newer" | "ask" | "keepBoth";
