// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerClaim } from "./PeerClaim";

/**
 * Information about a connected peer (visible to admin)
 */
export type ConnectedPeer = { endpointId: string, did: string, label: string | null, claims: Array<PeerClaim>, connectedAt: string, };
