// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the transport secures the connection to the mail server.
 */
export type ConnectionSecurity = "tls" | "startTls" | "none";
