// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The fields a principal may supply when inserting a NEW contact.
 *
 * There is deliberately **no `private_key` field** and **no `id` of an
 * existing row** — a principal can neither set a private key nor target an
 * existing identity. `source` is validated to be `'contact'`.
 */
export type ContactInsert = { did: string, name: string, 
/**
 * Must be exactly `"contact"`. Present so a caller can't smuggle
 * `source='own'`; validated by [`validate_contact_insert`].
 */
source: string, avatar: string | null, avatarOptions: string | null, notes: string | null, };
