// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gets statistics about CRDT tables
 */
export type CrdtStats = { 
/**
 * Total number of rows across all CRDT tables
 */
totalEntries: bigint, 
/**
 * Number of tables with dirty changes (kept for backwards compatibility)
 */
pendingUpload: bigint, 
/**
 * Number of CRDT-enabled tables (kept for backwards compatibility)
 */
pendingApply: bigint, 
/**
 * Number of non-tombstoned entries
 */
applied: bigint, 
/**
 * Total count across all tables (kept for backwards compatibility)
 */
insertCount: bigint, 
/**
 * Number of non-tombstoned entries (kept for backwards compatibility)
 */
updateCount: bigint, 
/**
 * Number of tombstoned (soft-deleted) entries
 */
deleteCount: bigint, };
