// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Gets statistics about CRDT tables
 */
export type CrdtStats = { 
/**
 * Total number of rows across all CRDT tables
 */
totalEntries: number, 
/**
 * Number of tables with dirty changes (kept for backwards compatibility)
 */
pendingUpload: number, 
/**
 * Number of CRDT-enabled tables (kept for backwards compatibility)
 */
pendingApply: number, 
/**
 * Number of non-tombstoned entries
 */
applied: number, 
/**
 * Total count across all tables (kept for backwards compatibility)
 */
insertCount: number, 
/**
 * Number of non-tombstoned entries (kept for backwards compatibility)
 */
updateCount: number, 
/**
 * Number of tombstoned (soft-deleted) entries
 */
deleteCount: number, };
