// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the CRDT layer's contents. Thin vault-side mirror of
 * `haex_crdt::CrdtStats` — see `CleanupResult` for the ts-rs rationale.
 */
export type CrdtStats = { 
/**
 * Live rows across every CRDT-managed table (identified by the presence
 * of the row-level HLC column). Excludes `_no_sync` tables, SQLite
 * internals, and the delete-log table itself.
 */
liveRowCount: bigint, 
/**
 * Number of CRDT-managed tables discovered.
 */
crdtTableCount: bigint, 
/**
 * Rows currently in `haex_deleted_rows`.
 */
deleteLogRowCount: bigint, };
