// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic discriminator for a critical failure. One variant per distinct
 * failure class — never reused across call sites that have semantically
 * different recovery paths. Frontend uses this as the i18n key for the
 * banner's title/description/risk/action quad.
 *
 * **Adding a new code:**
 * 1. Add the variant here.
 * 2. Wire its severity below in [`Self::severity`].
 * 3. Add the four i18n strings (title/description/risk/action) under
 *    `critical_failures.<VariantName>` in `src/locales/{de,en}.yml`.
 * 4. The ts-rs export regenerates the TypeScript union automatically;
 *    Vue-i18n's `missing-keys` check catches forgotten translations at
 *    compile time.
 *
 * **Why string discriminator (the default `Serialize` shape) instead of a
 * numeric tag:** the DB row stores the variant name as text, so an
 * operator can grep `haex_critical_notifications_no_sync` directly. A
 * numeric tag would require a separate code → name map.
 */
export type CriticalFailureCode = "HlcMutexPoisoned" | "DbMutexPoisoned" | "DbSchemaDrift" | "AuditLogWriteFailed" | "CrdtTransformFailed";
