// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row from `haex_critical_notifications_no_sync`, shaped for the
 * frontend banner. ts-rs export keeps the TypeScript type in sync.
 */
export type CriticalNotification = { id: string, 
/**
 * Stable discriminator (see [`CriticalFailureCode`]).
 */
code: string, 
/**
 * Source location — diagnostic only, NOT in the banner message.
 */
location: string, 
/**
 * JSON object for i18n parameter substitution. Stored as a string in
 * the DB to keep the table SQLite-portable.
 */
params: string, 
/**
 * Number of times this (code, location, acknowledged) tuple has fired.
 */
count: bigint, firstSeen: string, lastSeen: string, acknowledged: boolean, };
