// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteLogEntry } from "./DeleteLogEntry";
import type { ExtensionStats } from "./ExtensionStats";
import type { PendingSyncInfo } from "./PendingSyncInfo";

/**
 * Comprehensive database information
 */
export type DatabaseInfo = { 
/**
 * Database file size in bytes
 */
fileSizeBytes: bigint, 
/**
 * Database file size formatted (e.g., "2.5 MB")
 */
fileSizeFormatted: string, 
/**
 * Statistics grouped by extension
 */
extensions: Array<ExtensionStats>, 
/**
 * Pending sync information
 */
pendingSync: Array<PendingSyncInfo>, 
/**
 * Total pending sync entries
 */
totalPendingSync: bigint, 
/**
 * Delete-log entries (limited to most recent)
 */
deleteLogEntries: Array<DeleteLogEntry>, 
/**
 * Total delete-log rows across all tables
 */
totalDeleteLogRows: bigint, 
/**
 * Total entries across all CRDT tables
 */
totalEntries: bigint, 
/**
 * Total active entries
 */
totalActive: bigint, };
