// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtensionStats } from "./ExtensionStats";
import type { PendingSyncInfo } from "./PendingSyncInfo";
import type { TombstoneEntry } from "./TombstoneEntry";

/**
 * Comprehensive database information
 */
export type DatabaseInfo = { 
/**
 * Database file size in bytes
 */
fileSizeBytes: bigint, 
/**
 * Database file size formatted (e.g., "2.5 MB")
 */
fileSizeFormatted: string, 
/**
 * Statistics grouped by extension
 */
extensions: Array<ExtensionStats>, 
/**
 * Pending sync information
 */
pendingSync: Array<PendingSyncInfo>, 
/**
 * Total pending sync entries
 */
totalPendingSync: number, 
/**
 * Tombstone entries (limited to most recent)
 */
tombstones: Array<TombstoneEntry>, 
/**
 * Total tombstone count across all tables
 */
totalTombstones: number, 
/**
 * Total entries across all CRDT tables
 */
totalEntries: number, 
/**
 * Total active entries
 */
totalActive: number, };
