// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How to handle deletions during sync
 */
export type DeleteMode = "trash" | "permanent" | "ignore";
