// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectedPeer } from "./ConnectedPeer";

/**
 * Status of the local delivery service
 */
export type DeliveryStatus = { isLeader: boolean, activeSpaces: Array<string>, connectedPeers: Array<ConnectedPeer>, bufferedMessages: number, bufferedWelcomes: number, bufferedKeyPackages: number, };
