// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Device type classification (for UI icons)
 */
export type DeviceType = "mobile" | "desktop" | "web" | "headless" | "server";
