// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KnownDevice } from "./KnownDevice";

export type DeviceResolution = { 
/**
 * The OS-level device id (= contents of `<app_data>/device_id`).
 */
deviceId: string, 
/**
 * `Some(id)` when a `haex_devices` row with this `device_id` exists and
 * can be reused silently.
 */
matchedId: string | null, 
/**
 * `Some(endpoint_id)` when matched — convenience for callers that want
 * to start the iroh endpoint immediately.
 */
matchedEndpointId: string | null, 
/**
 * All `haex_devices` rows in the open vault. Used by the reconciliation
 * dialog so the user can either pick a known device row to claim or
 * register a fresh row.
 */
knownDevices: Array<KnownDevice>, };
