// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

/**
 * A discovered remote device
 */
export type Device = { 
/**
 * Human-readable device name
 */
alias: string, 
/**
 * Protocol version
 */
version: string, 
/**
 * Device model
 */
deviceModel: string | null, 
/**
 * Device type for UI
 */
deviceType: DeviceType, 
/**
 * SHA-256 fingerprint of device's TLS certificate
 */
fingerprint: string, 
/**
 * IP address
 */
address: string, 
/**
 * Port
 */
port: number, 
/**
 * Protocol (http or https)
 */
protocol: string, 
/**
 * Whether device supports download mode
 */
download: boolean, 
/**
 * Last seen timestamp (Unix millis)
 */
lastSeen: bigint, };
