// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceType } from "./DeviceType";

/**
 * Our device information
 */
export type DeviceInfo = { 
/**
 * Human-readable device name
 */
alias: string, 
/**
 * Protocol version
 */
version: string, 
/**
 * Device model (e.g., "Linux", "MacBook Pro")
 */
deviceModel: string | null, 
/**
 * Device type for UI
 */
deviceType: DeviceType, 
/**
 * SHA-256 fingerprint of our TLS certificate
 */
fingerprint: string, 
/**
 * Port we're listening on
 */
port: number, 
/**
 * Protocol (http or https)
 */
protocol: string, 
/**
 * Whether we support download mode (browser mode)
 */
download: boolean, };
