// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Directory entry
 */
export type DirEntry = { 
/**
 * Entry name (not full path)
 */
name: string, 
/**
 * Full path
 */
path: string, 
/**
 * True if this is a file
 */
isFile: boolean, 
/**
 * True if this is a directory
 */
isDirectory: boolean, 
/**
 * File size in bytes (0 for directories)
 */
size: bigint, 
/**
 * Last modified time (Unix timestamp in milliseconds)
 */
modified: bigint | null, };
