// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirEntry } from "./DirEntry";

/**
 * Paginated directory listing
 */
export type DirListing = { entries: Array<DirEntry>, total: number, };
