// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request a resumable streaming download into a local file.
 *
 * `transfer_id` is a frontend-generated UUID so the WebView can correlate
 * `storage:transfer:*` events to a specific UI row and (optionally) cancel
 * the transfer via [`remote_storage_cancel_transfer`].
 */
export type DownloadToPathRequest = { 
/**
 * Backend ID to download from
 */
backendId: string, 
/**
 * Object key (path in the bucket)
 */
key: string, 
/**
 * Absolute path on disk where the object should land. If the file
 * already exists, the download resumes from its current size.
 */
outputPath: string, 
/**
 * Caller-generated transfer id, used to route progress events and
 * cancellation requests.
 */
transferId: string, };
