// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of a leader election, exposed to frontend.
 */
export type ElectionResultInfo = { 
/**
 * "leader", "peer", or "none"
 */
role: string, leaderEndpointId: string | null, leaderPriority: number | null, leaderRelayUrl: string | null, };
