// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableStats } from "./TableStats";

/**
 * Statistics grouped by extension or system
 */
export type ExtensionStats = { 
/**
 * Extension UUID from haex_extensions table, or null for system tables
 */
extensionId: string | null, 
/**
 * Extension name (e.g., "haex-pass") or "System" for core tables
 */
name: string, 
/**
 * Tables belonging to this extension
 */
tables: Array<TableStats>, 
/**
 * Total rows across all tables
 */
totalRows: number, 
/**
 * Total active rows across all tables
 */
activeRows: number, 
/**
 * Total tombstone rows across all tables
 */
tombstoneRows: number, };
