// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayMode } from "./DisplayMode";
import type { ExtensionPermissions } from "./ExtensionPermissions";
import type { ManifestI18nEntry } from "./ManifestI18nEntry";

export type ExtensionManifest = { name: string, version: string, author: string | null, entry: string | null, icon: string | null, publicKey: string, signature: string, permissions: ExtensionPermissions, homepage: string | null, description: string | null, singleInstance: boolean | null, displayMode: DisplayMode | null, 
/**
 * Path to the migrations directory relative to the extension root.
 * Contains Drizzle-style migrations with _journal.json and *.sql files.
 * Example: "database/migrations"
 */
migrationsDir: string | null, 
/**
 * Locale-specific overrides for name, description, etc.
 * Key is locale code (e.g. "de", "en"), value contains localized fields.
 */
i18n: { [key in string]: ManifestI18nEntry } | null, };
