// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response with extension limits
 */
export type ExtensionLimitsResponse = { extensionId: string, queryTimeoutMs: bigint, maxResultRows: bigint, maxConcurrentQueries: bigint, maxQuerySizeBytes: bigint, 
/**
 * Whether custom limits are configured (false = using defaults)
 */
isCustom: boolean, };
