// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aktion für externe-Client-Zugriffe auf eine Extension über die Bridge.
 *
 * Single-Variant analog zu `NotificationsAction` — der eigentliche Scope
 * steckt im `target` (`"{extension_public_key}::{extension_name}::{action}"`,
 * Wildcard `…::*`), nicht in dieser Aktion selbst. Existiert primär, damit
 * `Action::ExtensionApi(...)` einen typsicheren Wert braucht.
 */
export type ExtensionApiAction = "call";
