// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PermissionEntry } from "./PermissionEntry";

/**
 * Definiert die einheitliche Struktur für alle Berechtigungsarten im Manifest und UI.
 */
export type ExtensionPermissions = { database: Array<PermissionEntry> | null, filesystem: Array<PermissionEntry> | null, http: Array<PermissionEntry> | null, shell: Array<PermissionEntry> | null, filesync: Array<PermissionEntry> | null, spaces: Array<PermissionEntry> | null, identities: Array<PermissionEntry> | null, passwords: Array<PermissionEntry> | null, };
