// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Action } from "./Action";
import type { PermissionConstraints } from "./PermissionConstraints";
import type { PermissionStatus } from "./PermissionStatus";
import type { ResourceType } from "./ResourceType";

/**
 * Die interne Repräsentation einer einzelnen, gewährten Berechtigung.
 */
export type ExtensionPermission = { id: string, extensionId: string, resourceType: ResourceType, action: Action, target: string, constraints: PermissionConstraints | null, status: PermissionStatus, };
