// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selector for `fetch_envelopes` / `fetch_message`.
 */
export type FetchRange = { "type": "latest", count: number, } | { "type": "uidRange", start: number, end: number, } | { "type": "uidList", uids: Array<number>, };
