// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a single file or directory.
 * Both local scans and remote manifests produce `Vec<FileState>`.
 */
export type FileState = { relativePath: string, size: bigint, 
/**
 * Unix timestamp in seconds
 */
modifiedAt: bigint, isDirectory: boolean, 
/**
 * SHA-256 of file content as lowercase hex. `None` for directories or
 * when the provider has not (yet) computed it. The diff engine uses this
 * for authoritative equality — timestamps alone are unreliable because
 * `write` resets mtime on the receiver.
 */
hash?: string, };
