// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File/directory metadata
 */
export type FileStat = { 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * True if this is a file
 */
isFile: boolean, 
/**
 * True if this is a directory
 */
isDirectory: boolean, 
/**
 * True if this is a symbolic link
 */
isSymlink: boolean, 
/**
 * Last modified time (Unix timestamp in milliseconds)
 */
modified: bigint | null, 
/**
 * Created time (Unix timestamp in milliseconds)
 */
created: bigint | null, 
/**
 * Whether the file is read-only
 */
readonly: boolean, };
