// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen, die auf FileSync (Cloud-Sync) angewendet werden können.
 */
export type FileSyncAction = "read" | "readWrite";
