// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChangeType } from "./FileChangeType";

/**
 * Event emitted when files change in a watched directory
 */
export type FileChangeEvent = { 
/**
 * The sync rule ID that was affected
 */
ruleId: string, 
/**
 * Type of change
 */
changeType: FileChangeType, 
/**
 * Relative path of the changed file (if available)
 */
path: string | null, };
