// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a single file or directory.
 * Both local scans and remote manifests produce `Vec<FileState>`.
 */
export type FileState = { relativePath: string, size: bigint, 
/**
 * Unix timestamp in seconds
 */
modifiedAt: bigint, isDirectory: boolean, 
/**
 * BLAKE3 of the full file, lowercase hex. None for directories.
 */
hash?: string, 
/**
 * Chunk size in bytes. None for directories.
 */
chunkSize?: number, 
/**
 * BLAKE3 hash of each chunk, lowercase hex, in order. None for directories;
 * empty Vec is invalid for files.
 */
chunkHashes?: Array<string>, };
