// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSyncState } from "./FileSyncState";

export type FileInfo = { id: string, spaceId: string, name: string, path: string, mimeType: string | null, size: bigint, contentHash: string, isDirectory: boolean, syncState: FileSyncState, backends: Array<string>, createdAt: string, updatedAt: string, };
