// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * File metadata for transfer
 */
export type FileInfo = { 
/**
 * Unique file ID within the transfer
 */
id: string, 
/**
 * File name
 */
fileName: string, 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * MIME type
 */
fileType: string, 
/**
 * SHA-256 hash (optional, for verification)
 */
sha256: string | null, 
/**
 * Base64 preview thumbnail (optional)
 */
preview: string | null, 
/**
 * Relative path for folders (e.g., "folder/subfolder/file.txt")
 */
relativePath: string | null, };
