// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileSpace = { id: string, name: string, isPersonal: boolean, fileCount: bigint, totalSize: bigint, createdAt: string, updatedAt: string, };
