// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChangeType } from "./FileChangeType";

/**
 * Event emitted when files change in a watched directory (desktop only)
 */
export type FileChangeEvent = { 
/**
 * The sync rule ID that was affected
 */
ruleId: string, 
/**
 * Type of change
 */
changeType: FileChangeType, 
/**
 * Relative path of the changed file (if available)
 */
path: string | null, 
/**
 * Extensions that are currently allowed to read this path. Used by the
 * frontend broadcast layer to scope the fan-out to only authorized
 * extensions. Computed at emit time against both DB and session
 * permissions (no prompts).
 *
 * The list is for main-window-only consumption — it must never be
 * forwarded into extension iframes (they'd learn which *other*
 * extensions have access to the path).
 */
readerExtensionIds: Array<string>, };
