// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueStatus } from "./QueueStatus";

/**
 * Request to get queue entries
 */
export type GetQueueRequest = { 
/**
 * Filter by rule ID (optional)
 */
ruleId: string | null, 
/**
 * Filter by status (optional)
 */
status: QueueStatus | null, 
/**
 * Include completed entries (default: false)
 */
includeCompleted: boolean | null, };
