// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen, die auf Identitäten angewendet werden können.
 *
 * Read = list/view identities + contacts. Write = add a NEW contact only
 * (private_key NULL); never returns/sets private_key, never creates/deletes
 * owned identities. Enforcement lives in the identity bridge commands
 * (later phase).
 */
export type IdentityAction = "read" | "write";
