// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen, die auf Identitäten angewendet werden können.
 * Read-only: Extensions können Identitäten nur auflisten/anzeigen.
 * Erstellen und Löschen bleibt haex-vault vorbehalten.
 */
export type IdentityAction = "read";
