// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The `private_key`-free view of an identity returned to a principal on read.
 *
 * SECURITY: this struct intentionally has **no `private_key` field**. The
 * secret cannot be serialized to a principal because there is nowhere to put
 * it — masking is enforced by the type, not by a runtime check. Covers both
 * own identities and contacts (the shape is identical; only `source` differs).
 */
export type IdentityReadView = { id: string, did: string, name: string, source: string, avatar: string | null, avatarOptions: string | null, notes: string | null, };
