// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSecurity } from "./ConnectionSecurity";

/**
 * IMAP server configuration + credentials.
 */
export type ImapConfig = { host: string, port: number, security: ConnectionSecurity, username: string, password: string, };
