// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnownDevice = { id: string, ownerDid: string, 
/**
 * `None` for foreign device stubs (created by the
 * `haex_space_devices_ensure_refs` trigger) — those rows never carry the
 * file UUID because we don't own the physical device.
 */
deviceId: string | null, endpointId: string, name: string, platform: string, avatar: string | null, avatarOptions: string | null, createdAt: string | null, };
