// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnownDevice = { id: string, deviceId: string, endpointId: string, name: string, platform: string, avatar: string | null, avatarOptions: string | null, createdAt: string | null, };
