// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ListFilesRequest = { spaceId: string, path: string | null, recursive: boolean | null, };
