// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * LocalSend settings
 */
export type LocalSendSettings = { 
/**
 * Device alias
 */
alias: string, 
/**
 * Port to use
 */
port: number, 
/**
 * Auto-accept transfers from known devices
 */
autoAccept: boolean, 
/**
 * Default save directory
 */
saveDirectory: string | null, 
/**
 * Require PIN for incoming transfers
 */
requirePin: boolean, 
/**
 * PIN (if require_pin is true)
 */
pin: string | null, 
/**
 * Show notification on incoming transfer
 */
showNotifications: boolean, };
