// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local file information (not encrypted, for UI display)
 */
export type LocalFileInfo = { 
/**
 * Unique identifier (local path hash)
 */
id: string, 
/**
 * File name
 */
name: string, 
/**
 * Full local path
 */
path: string, 
/**
 * Relative path from sync root
 */
relativePath: string, 
/**
 * MIME type (if detected)
 */
mimeType: string | null, 
/**
 * File size in bytes
 */
size: bigint, 
/**
 * Whether this is a directory
 */
isDirectory: boolean, 
/**
 * Last modified time (ISO 8601)
 */
modifiedAt: string | null, };
