// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about a local invite token (exposed to frontend).
 */
export type LocalInviteInfo = { id: string, targetDid: string | null, capability: string, maxUses: number, currentUses: number, expiresAt: string, };
