// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aktionen auf dem Mail-Modul (IMAP fetch + SMTP send).
 *
 * Der natürliche Split bei Mail ist Protokoll-basiert (IMAP vs SMTP),
 * nicht read/write — IMAP-Server und SMTP-Server sind oft unterschiedliche
 * Hosts. `target` ist der Mailserver-Hostname (z.B. "imap.gmail.com")
 * oder "*" als Wildcard. Subdomain-Match: target="gmail.com" matched
 * "imap.gmail.com" und "smtp.gmail.com".
 *
 * `Fetch` umfasst alle IMAP-Operationen (LIST, FETCH, STORE/Flags, MOVE,
 * DELETE, APPEND) — extra read/write-Trennung lohnt nicht, weil "lesen"
 * bei IMAP bereits den vollen Datenzugriff bedeutet.
 */
export type MailAction = "fetch" | "send";
