// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Mailbox / folder metadata returned by LIST + STATUS.
 */
export type MailboxInfo = { name: string, delimiter: string | null, 
/**
 * Mailbox flags reported by LIST (e.g. "\\HasNoChildren", "\\Marked").
 */
flags: Array<string>, 
/**
 * Total message count (only set if STATUS was queried).
 */
exists: number | null, 
/**
 * Unseen / unread count.
 */
unseen: number | null, 
/**
 * UIDVALIDITY — if it changes the local UID-cache must be invalidated.
 */
uidValidity: number | null, 
/**
 * UIDNEXT — predicted UID of the next arriving message.
 */
uidNext: number | null, };
