// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Localized fields for a specific locale (e.g. "de", "en")
 */
export type ManifestI18nEntry = { name: string | null, description: string | null, };
