// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Attachment } from "./Attachment";
import type { MessageEnvelope } from "./MessageEnvelope";

/**
 * Full message: envelope + parsed body parts + attachment metadata.
 *
 * Attachment data is NOT included by default — request individual
 * attachments via a separate fetch (TODO: dedicated attachment API).
 */
export type Message = { envelope: MessageEnvelope, bodyText: string | null, bodyHtml: string | null, attachments: Array<Attachment>, };
