// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";

/**
 * Lightweight message summary for list views (no body).
 *
 * `references` and `in_reply_to` enable client-side threading.
 */
export type MessageEnvelope = { uid: number, 
/**
 * IMAP per-flags (e.g. "\\Seen", "\\Answered", "\\Flagged").
 */
flags: Array<string>, 
/**
 * Server-side internal date as Unix timestamp (seconds).
 */
internalDate: bigint | null, subject: string | null, from: Array<Address>, to: Array<Address>, cc: Array<Address>, messageId: string | null, inReplyTo: string | null, references: Array<string>, size: number | null, };
