// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlsCommitBundle = { commit: Array<number>, welcome: Array<number> | null, groupInfo: Array<number>, 
/**
 * UCAN token bytes the committer holds for the space. Present iff the
 * commit is membership-changing AND the committing device holds
 * `Invite`-or-higher. Absent for application messages, key rotations,
 * self-leaves, and leader-rekey-after-self-leave (where every removed
 * leaf's DID is already gone from `haex_space_members`, so the
 * receiver's target-gone exemption applies and no proof is needed).
 * Travels alongside `commit` from `mls_remove_member` down to
 * `local_delivery_broadcast_commit` and out onto the wire via
 * `Request::MlsSendMessage::committer_ucan`. See
 * `mls::authorization::authorize_committer_capability` (plan §5.8).
 */
committerUcan: Array<number> | null, 
/**
 * ed25519 signature over
 * `sha256("haex-mls-commit-bind-v1" || sha256(commit))`, produced
 * with the identity key resolvable from `committer_ucan`'s
 * `audience_did`. Prevents UCAN replay against a different commit.
 * Present iff `committer_ucan` is present.
 */
committerCommitBindSig: Array<number> | null, };
