// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlsCommitBundle = { commit: Array<number>, welcome: Array<number> | null, groupInfo: Array<number>, 
/**
 * Raw UCAN JWT token the committer holds for the space. A UCAN's own
 * dot-separated segments are already base64url and safe as JSON text,
 * so it is carried as a plain `String` — no outer base64 wrap on the
 * wire, no lossy byte round-trip in storage.
 *
 * Only attached by `MlsManager::remove_member` today, and only when
 * `authorize_local_removal` reports `proof_required = true` — i.e. the
 * Remove targets an ACTIVE member and the committer holds
 * `Invite`-or-higher. Absent for `add_member` (invite-token authority
 * gates that upstream), self-leaves, and leader-rekey-after-self-leave
 * where every removed leaf's DID is already gone from
 * `haex_space_members` on this committer so the receiver's target-gone
 * exemption applies. Travels from `remove_member` down to
 * `local_delivery_broadcast_commit` and out onto the wire via
 * `Request::MlsSendMessage::committer_ucan`. See
 * `mls::authorization::authorize_committer_capability` (plan §5.8).
 */
committerUcan: string | null, 
/**
 * ed25519 signature over
 * `sha256("haex-mls-commit-bind-v1" || sha256(commit))`, produced
 * with the identity key resolvable from `committer_ucan`'s
 * `audience_did`. Prevents UCAN replay against a different commit.
 * Attached under the same `proof_required` condition as
 * `committer_ucan`; present iff `committer_ucan` is present.
 */
committerCommitBindSig: Array<number> | null, };
