// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MlsCommitBundle = { commit: Array<number>, welcome: Array<number> | null, groupInfo: Array<number>, };
