// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MlsEpochKey } from "./MlsEpochKey";

/**
 * Result of joining a group via External Commit.
 * Contains the commit (to be sent to server/leader) and the new epoch key.
 */
export type MlsExternalCommitResult = { commit: Array<number>, epochKey: MlsEpochKey, };
