// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A freshly-generated KeyPackage paired with its proof-of-possession —
 * see `mls::pop` for what the signature attests.
 */
export type MlsKeyPackageWithPop = { keyPackage: Array<number>, pop: Array<number>, };
