// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aktionen auf dem generischen Notifications-Modul.
 *
 * Aktuell nur `Show` (OS-Notification anzeigen). `target` ist immer "*" —
 * Notifications sind nicht ressourcen-gescoped; die Identität wird über den
 * Public Key der aufrufenden Extension gepinnt (siehe `extension::notifications`).
 */
export type NotificationsAction = "show";
