// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of an outbox delivery attempt.
 *
 * Distinguishes transient (retry until `expiresAt`) from permanent (mark
 * FAILED immediately) failures. Returned by `local_delivery_push_invite`
 * instead of a bare `String` so the outbox processor can classify the
 * failure without resorting to error-message string matching.
 */
export type OutboxAttemptError = { reason: string, 
/**
 * `true` if the failure is a network/liveness condition that may
 * succeed on a future attempt (recipient offline, relay flaky,
 * connect timeout). `false` for protocol/auth rejections that will
 * never succeed without intervention (UCAN audience mismatch,
 * signature failure, unknown capability).
 */
transient: boolean, };
