// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { OutgoingAttachment } from "./OutgoingAttachment";

/**
 * Outgoing message for SMTP send.
 */
export type OutgoingMessage = { from: Address, to: Array<Address>, cc: Array<Address>, bcc: Array<Address>, replyTo?: Address | null, subject: string, bodyText: string | null, bodyHtml: string | null, attachments: Array<OutgoingAttachment>, 
/**
 * Message-ID being replied to. Sets `In-Reply-To` header.
 */
inReplyTo: string | null, 
/**
 * Threading chain. Sets `References` header.
 */
references: Array<string>, };
