// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outgoing attachment. `data` is base64-encoded — matches the web
 * module's wire format for binary payloads. The SMTP layer decodes
 * before building the MIME part.
 */
export type OutgoingAttachment = { filename: string, contentType: string, 
/**
 * Base64-encoded bytes (standard alphabet, with padding).
 */
data: string, 
/**
 * If `Some`, sets `Content-ID` and the part is marked inline
 * (referenced by `cid:` URLs in `body_html`).
 */
contentId: string | null, };
