// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Links an item to a stored binary. File name may differ per-item even when
 * the underlying binary (hash) is shared.
 */
export type PasswordItemBinary = { id: string, itemId: string, binaryHash: string, fileName: string, };
