// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Core password record. Row type for `haex_passwords_items`.
 * OTP fields are inline (1:1 relation with the item). All other relations
 * are separate tables (see below).
 */
export type PasswordItem = { id: string, title: string | null, username: string | null, password: string | null, note: string | null, icon: string | null, color: string | null, url: string | null, otpSecret: string | null, otpDigits: number | null, otpPeriod: number | null, otpAlgorithm: string | null, 
/**
 * Maps canonical field names to autofill aliases for browser matching.
 * Stored as JSON text in the DB.
 * e.g. `{ "username": ["email", "login"], "password": ["pass"] }`
 */
autofillAliases: { [key in string]: Array<string> } | null, expiresAt: string | null, createdAt: string | null, updatedAt: string | null, };
