// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * **UI-only organization.** Folders for visual grouping.
 * Not used for extension permission scoping — that is the Tag's job.
 */
export type PasswordGroup = { id: string, name: string | null, description: string | null, icon: string | null, color: string | null, sortOrder: number | null, parentId: string | null, createdAt: string | null, updatedAt: string | null, };
