// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PasswordKeyValue } from "./PasswordKeyValue";

/**
 * Full password item with relations, returned by `extension_password_read`.
 *
 * Includes secret fields (password, otp_secret). Attachments and passkeys
 * have their own bridge commands and are NOT returned here to avoid pulling
 * large base64 blobs into every read.
 */
export type PasswordItemFull = { id: string, title: string | null, username: string | null, password: string | null, note: string | null, icon: string | null, color: string | null, url: string | null, otpSecret: string | null, otpDigits: bigint | null, otpPeriod: bigint | null, otpAlgorithm: string | null, 
/**
 * Maps canonical field names to autofill aliases for browser matching.
 * e.g. `{ "username": ["email", "login"], "password": ["pass"] }`
 */
autofillAliases: { [key in string]: Array<string> } | null, tags: Array<string>, keyValues: Array<PasswordKeyValue>, expiresAt: string | null, createdAt: string | null, updatedAt: string | null, };
