// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PasswordGeneratorPreset = { id: string, name: string, length: number, uppercase: boolean, lowercase: boolean, numbers: boolean, symbols: boolean, excludeChars: string | null, usePattern: boolean, pattern: string | null, isDefault: boolean, createdAt: string | null, updatedAt: string | null, };
