// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aktionen auf dem Core-Passworttresor.
 *
 * Scope wird über `ExtensionPermission.target` als Tag-Filter gesteuert
 * (z.B. target="calendar" => nur Items mit Tag "calendar", target="*" => alle).
 * Writes müssen mindestens ein Tag innerhalb des erlaubten Scopes setzen –
 * Enforcement geschieht in den Bridge-Commands.
 */
export type PasswordsAction = "read" | "readWrite";
