// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PasswordKeyValueInput } from "./PasswordKeyValueInput";

/**
 * Input for create & update operations.
 *
 * `tags` is required and must contain at least one tag within the
 * extension's permission scope (variant B enforcement). Items outside the
 * extension's own scope cannot be created — the write is rejected.
 */
export type PasswordInput = { title: string | null, username: string | null, password: string | null, note: string | null, icon: string | null, color: string | null, url: string | null, otpSecret: string | null, otpDigits: bigint | null, otpPeriod: bigint | null, otpAlgorithm: string | null, autofillAliases: { [key in string]: Array<string> } | null, expiresAt: string | null, tags: Array<string>, keyValues: Array<PasswordKeyValueInput>, };
