// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attachments and icons. Primary key is the SHA-256 hash, so identical
 * binaries across items/snapshots deduplicate automatically.
 */
export type PasswordBinary = { hash: string, 
/**
 * Base64-encoded binary data.
 */
data: string, size: bigint, 
/**
 * "attachment" or "icon".
 */
kind: string | null, createdAt: string | null, };
