// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Point-in-time snapshot of an item. Contents serialized as JSON in
 * `snapshot_data` so the history format stays stable if `PasswordItem`
 * evolves later.
 */
export type PasswordItemSnapshot = { id: string, itemId: string, 
/**
 * JSON: serialized item state (excluding binaries — those are linked
 * via `haex_passwords_snapshot_binaries`).
 */
snapshotData: string, createdAt: string | null, modifiedAt: string | null, };
