// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-defined extra field on an item (e.g. "Recovery Code", "PIN").
 */
export type PasswordItemKeyValue = { id: string, itemId: string, key: string | null, value: string | null, updatedAt: string | null, };
