// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lean view of a password item for lists.
 *
 * Does NOT include secret fields (password, otpSecret, private_key, ...).
 * Full details require a separate `extension_password_read` call, which
 * allows the core to audit per-record reads.
 */
export type PasswordItemSummary = { id: string, title: string | null, username: string | null, url: string | null, icon: string | null, color: string | null, tags: Array<string>, createdAt: string | null, updatedAt: string | null, };
