// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tags drive **logical classification**, including the permission scope
 * that extensions receive. First-class entities with color and unique name.
 */
export type PasswordTag = { id: string, name: string, color: string | null, createdAt: string | null, };
