// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * WebAuthn credential. Either linked to a `PasswordItem` (displayed inside
 * the corresponding login entry) or standalone (discoverable resident-key
 * passkey not tied to a classical login).
 */
export type PasswordPasskey = { id: string, itemId: string | null, 
/**
 * Unique per credential (WebAuthn requirement).
 */
credentialId: string, relyingPartyId: string, relyingPartyName: string | null, userHandle: string, userName: string | null, userDisplayName: string | null, 
/**
 * PKCS8 format, Base64-encoded.
 */
privateKey: string, 
/**
 * SPKI format, Base64-encoded.
 */
publicKey: string, 
/**
 * COSE algorithm: -7 = ES256, -8 = EdDSA, -257 = RS256.
 */
algorithm: number, 
/**
 * Replay-protection counter. Incremented on every authentication use.
 */
signCount: bigint, isDiscoverable: boolean, icon: string | null, color: string | null, nickname: string | null, createdAt: string | null, lastUsedAt: string | null, };
