// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ergebnis einer Passwords-Permission-Prüfung.
 *
 * Beschreibt welche Tag-Scopes eine Extension für die angefragte Aktion lesen
 * bzw. schreiben darf. Wird von den Bridge-Commands verwendet um SQL-Queries
 * auf die erlaubten Tags zu begrenzen.
 */
export type PasswordsScope = { "type": "all" } | { "type": "tags", tags: Array<string>, default: string | null, };
