// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted to the frontend whenever a peer's verified DID-auth handshake
 * completes — both when we accept an inbound connection and when an
 * outbound connection finishes its client-side handshake.
 *
 * The outbox processor uses this to flush any PENDING rows that target
 * this endpoint without waiting for its scheduled `nextRetryAt`.
 */
export type PeerConnectedEvent = { 
/**
 * Iroh `EndpointId` of the verified peer, as the same hex string the
 * outbox stores in `haex_invite_outbox.targetEndpointId`.
 */
endpointId: string, 
/**
 * Verified DID, when the side that emits the event knows it. The
 * accept side always has it (post-handshake); the connect side may
 * emit `None` for paths that don't track the remote DID.
 */
verifiedDid: string | null, };
