// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Device } from "./Device";
import type { FileInfo } from "./FileInfo";

/**
 * Pending transfer request (for UI)
 */
export type PendingTransfer = { 
/**
 * Session ID
 */
sessionId: string, 
/**
 * Sender device info
 */
sender: Device, 
/**
 * Files to be received
 */
files: Array<FileInfo>, 
/**
 * Total size in bytes
 */
totalSize: bigint, 
/**
 * Whether PIN is required
 */
pinRequired: boolean, 
/**
 * Created timestamp (Unix millis)
 */
createdAt: bigint, };
