// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestedExtension } from "./RequestedExtension";

/**
 * Pending authorization request waiting for user approval
 */
export type PendingAuthorization = { 
/**
 * Unique client identifier
 */
clientId: string, 
/**
 * Human-readable client name
 */
clientName: string, 
/**
 * Client's public key (base64)
 */
publicKey: string, 
/**
 * Extensions the client wants to access
 * These should be pre-selected in the authorization dialog (matched by name + extensionPublicKey)
 */
requestedExtensions: Array<RequestedExtension>, };
