// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pending authorization request waiting for user approval
 */
export type PendingAuthorization = { 
/**
 * Unique client identifier
 */
clientId: string, 
/**
 * Human-readable client name
 */
clientName: string, 
/**
 * Client's public key (base64)
 */
publicKey: string, 
/**
 * Requested extension ID
 */
extensionId: string, };
