// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pending sync entry
 */
export type PendingSyncInfo = { 
/**
 * Table name with pending changes
 */
tableName: string, 
/**
 * When the table was last modified
 */
lastModified: string, 
/**
 * Number of rows that need to be synced (estimated)
 */
pendingRows: number, };
