// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Queue entry status
 */
export type QueueStatus = "pending" | "inProgress" | "completed" | "failed";
