// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncQueueEntry } from "./SyncQueueEntry";

/**
 * Aggregated queue status for a rule
 */
export type QueueSummary = { 
/**
 * Number of pending items
 */
pendingCount: number, 
/**
 * Number of in-progress items
 */
inProgressCount: number, 
/**
 * Number of completed items
 */
completedCount: number, 
/**
 * Number of failed items
 */
failedCount: number, 
/**
 * Total bytes pending (sum of file_size for pending items)
 */
pendingBytes: bigint, 
/**
 * Currently processing entry (if any)
 */
currentEntry: SyncQueueEntry | null, };
