// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file entry for adding to the queue
 */
export type QueueFileEntry = { 
/**
 * Full local path
 */
localPath: string, 
/**
 * Relative path from sync root
 */
relativePath: string, 
/**
 * File size in bytes
 */
fileSize: bigint, };
