// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Extension requested by an external client
 */
export type RequestedExtension = { 
/**
 * Extension name (e.g., "haex-pass")
 */
name: string, 
/**
 * Extension's public key (hex string from manifest)
 * Named differently from ClientInfo.public_key to avoid confusion
 */
extensionPublicKey: string, };
