// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourceType = "fs" | "web" | "db" | "shell" | "filesync" | "spaces" | "identities" | "passwords";
