// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generische Read/ReadWrite-Aktion, geteilt von den Sync-Ressourcen
 * (`SyncServers`, `CloudStorage`, `SyncRules`).
 */
export type RwAction = "read" | "readWrite";
