// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type S3BackendConfig = { endpoint: string | null, region: string, bucket: string, accessKeyId: string, secretAccessKey: string, 
/**
 * Use path-style URLs instead of virtual-hosted-style (for MinIO and some other services)
 */
usePathStyle: boolean | null, };
