// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBackendType } from "./StorageBackendType";

export type S3BackendConfig = { type: StorageBackendType, endpoint: string | null, region: string, bucket: string, accessKeyId: string, secretAccessKey: string, };
