// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S3-compatible backend configuration
 */
export type S3Config = { 
/**
 * Custom endpoint URL (for non-AWS S3-compatible services)
 */
endpoint: string | null, 
/**
 * AWS region or custom region name
 */
region: string, 
/**
 * Bucket name
 */
bucket: string, 
/**
 * Access key ID
 */
accessKeyId: string, 
/**
 * Secret access key
 */
secretAccessKey: string, 
/**
 * Use path-style URLs instead of virtual-hosted-style
 */
pathStyle: boolean | null, };
