// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * S3 config without secrets (for display purposes)
 */
export type S3PublicConfig = { 
/**
 * Custom endpoint URL (for non-AWS S3-compatible services)
 */
endpoint: string | null, 
/**
 * AWS region or custom region name
 */
region: string, 
/**
 * Bucket name
 */
bucket: string, };
