// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to scan local files in a sync rule folder
 */
export type ScanLocalRequest = { 
/**
 * Sync rule ID to get the local path from
 */
ruleId: string, 
/**
 * Optional subdirectory path relative to sync rule root
 */
subpath: string | null, };
