// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialized representation of ExtensionError for TypeScript.
 * Not constructed in Rust — serves as the schema for the auto-generated TS type via ts_rs.
 */
export type SerializedExtensionError = { code: number, type: string, message: string, extensionId: string | null, };
