// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server status information
 */
export type ServerStatus = { 
/**
 * Whether server is running
 */
running: boolean, 
/**
 * Port server is listening on
 */
port: number | null, 
/**
 * Our fingerprint
 */
fingerprint: string | null, 
/**
 * Local IP addresses
 */
addresses: Array<string>, };
