// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Server info returned when starting
 */
export type ServerInfo = { 
/**
 * Port server is listening on
 */
port: number, 
/**
 * Our fingerprint
 */
fingerprint: string, 
/**
 * Local IP addresses
 */
addresses: Array<string>, };
