// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session blocked client entry (for "deny once" blocks)
 */
export type SessionBlockedClient = { 
/**
 * Unique client identifier (public key fingerprint)
 */
clientId: string, 
/**
 * Human-readable client name
 */
clientName: string, 
/**
 * Client's public key (base64)
 */
publicKey: string, };
