// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session authorization entry (for "allow once" authorizations)
 */
export type SessionAuthorization = { 
/**
 * Unique client identifier (public key fingerprint)
 */
clientId: string, 
/**
 * Human-readable client name (e.g. "haex-pass Browser Extension")
 */
clientName: string, 
/**
 * Client's public key (base64)
 */
publicKey: string, 
/**
 * Extension ID this client can access
 */
extensionId: string, 
/**
 * Canonical JSON of the client's declared manifest at grant time (see
 * `protocol::canonical_requested_permissions`), compared against the
 * live handshake declaration on reconnect to detect a manifest change.
 */
requestedPermissions: string, };
