// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity is a property of the code (see Q2 in the plan), so the
 * frontend can branch on `Critical` vs `Warning` without consulting an
 * external table. Critical → red banner with "Restart vault" CTA;
 * Warning → orange banner with "Verstanden" only.
 */
export type Severity = "Critical" | "Warning";
