// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell exit event payload
 */
export type ShellExitEvent = { sessionId: string, exitCode: number | null, };
