// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell exit event payload. Includes `extension_id` for the same reason as
 * `ShellOutputEvent` — owner-scoped routing.
 */
export type ShellExitEvent = { sessionId: string, extensionId: string, exitCode: number | null, };
