// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Available shell info returned by list_available
 */
export type ShellInfo = { name: string, path: string, };
