// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell output event payload, emitted via Tauri events.
 *
 * `extension_id` identifies the owning extension so the broadcast layer can
 * route the event only to iframes of that extension — stdout must not leak
 * to other (potentially untrusted) extensions sharing the same origin.
 */
export type ShellOutputEvent = { sessionId: string, extensionId: string, data: string, };
