// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from shell create command
 */
export type ShellCreateResponse = { sessionId: string, 
/**
 * The resolved shell name (e.g., "bash", "zsh", "fish")
 */
shellName: string, };
