// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell session creation options
 */
export type ShellCreateOptions = { 
/**
 * Shell executable (e.g., "/bin/bash", "/bin/zsh"). If None, uses $SHELL or /bin/sh.
 */
shell: string | null, 
/**
 * Working directory. If None, uses home directory.
 */
cwd: string | null, 
/**
 * Initial terminal columns
 */
cols: number | null, 
/**
 * Initial terminal rows
 */
rows: number | null, 
/**
 * Environment variables to set
 */
env: { [key in string]: string } | null, };
