// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Shell output event payload, emitted via Tauri events
 */
export type ShellOutputEvent = { sessionId: string, data: string, };
