// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSecurity } from "./ConnectionSecurity";

/**
 * SMTP server configuration + credentials.
 */
export type SmtpConfig = { host: string, port: number, security: ConnectionSecurity, username: string, password: string, };
