// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Definiert Aktionen, die auf Shared Spaces angewendet werden können.
 * Read = Spaces lesen/anzeigen, ReadWrite = zusätzlich Spaces anlegen.
 */
export type SpaceAction = "read" | "readWrite";
