// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageBackendType } from "./StorageBackendType";

export type StorageBackendInfo = { id: string, type: StorageBackendType, name: string, enabled: boolean, createdAt: string, };
