// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { S3PublicConfig } from "./S3PublicConfig";

/**
 * Storage backend info (public, without credentials)
 */
export type StorageBackendInfo = { id: string, 
/**
 * Backend type (e.g., "s3")
 */
type: string, name: string, enabled: boolean, createdAt: string, 
/**
 * Public config (without secrets like access keys)
 */
config: S3PublicConfig | null, };
