// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Object info from list operation
 */
export type StorageObjectInfo = { 
/**
 * Object key
 */
key: string, 
/**
 * Size in bytes
 */
size: bigint, 
/**
 * Last modified timestamp (ISO 8601)
 */
lastModified: string | null, };
