// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to delete an object
 */
export type StorageDeleteRequest = { 
/**
 * Backend ID
 */
backendId: string, 
/**
 * Object key (path in the bucket)
 */
key: string, };
