// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to upload data
 */
export type StorageUploadRequest = { 
/**
 * Backend ID to upload to
 */
backendId: string, 
/**
 * Object key (path in the bucket)
 */
key: string, 
/**
 * Data as base64-encoded string
 */
data: string, };
