// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StorageObjectInfo } from "./StorageObjectInfo";

/**
 * Directory-style listing result: a single hierarchy level under a prefix,
 * split into sub-prefixes ("folders") and objects ("files"). Built on top of
 * S3's `delimiter` parameter so very large buckets aren't enumerated to
 * browse a single folder.
 */
export type StorageListDirResponse = { 
/**
 * Sub-prefixes under the requested prefix (always end with "/").
 */
folders: Array<string>, 
/**
 * Objects whose key starts with the prefix and contains no further "/".
 */
objects: Array<StorageObjectInfo>, };
