// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to download data
 */
export type StorageDownloadRequest = { 
/**
 * Backend ID to download from
 */
backendId: string, 
/**
 * Object key (path in the bucket)
 */
key: string, };
