// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncLogRow = { id: string, timestamp: string, level: string, 
/**
 * JSON payload `{ summary, raw? }` — kept as a string so the frontend
 * can parse it without an extra Tauri schema dance.
 */
message: string, deviceId: string, };
