// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result after executing a sync
 */
export type SyncResult = { filesDownloaded: number, filesDeleted: number, directoriesCreated: number, bytesTransferred: bigint, conflictsResolved: number, errors: Array<string>, };
