// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictStrategy } from "./ConflictStrategy";
import type { SyncDirection } from "./SyncDirection";

export type SyncRule = { id: string, 
/**
 * Device ID this sync rule belongs to (local paths are device-specific)
 */
deviceId: string, spaceId: string, localPath: string, backendIds: Array<string>, direction: SyncDirection, enabled: boolean, 
/**
 * Gitignore-like patterns for files/folders to exclude from sync
 */
ignorePatterns: Array<string>, 
/**
 * Default conflict resolution strategy for this sync rule
 */
conflictStrategy: ConflictStrategy, createdAt: string, updatedAt: string, };
