// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress update during sync execution
 */
export type SyncProgress = { currentFile: string, filesDone: number, filesTotal: number, bytesDone: bigint, bytesTotal: bigint, 
/**
 * Files currently being transferred in parallel
 */
activeFiles: Array<string>, 
/**
 * Current transfer rate in bytes/second
 */
bytesPerSecond: bigint, };
