// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncError } from "./SyncError";

export type SyncStatus = { isSyncing: boolean, pendingUploads: number, pendingDownloads: number, lastSync: string | null, errors: Array<SyncError>, };
