// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueOperation } from "./QueueOperation";
import type { QueueStatus } from "./QueueStatus";

/**
 * A sync queue entry representing a pending or in-progress file operation
 */
export type SyncQueueEntry = { id: string, 
/**
 * Device ID this entry belongs to
 */
deviceId: string, 
/**
 * Sync rule ID
 */
ruleId: string, 
/**
 * Full local path
 */
localPath: string, 
/**
 * Relative path from sync root (used as remote path)
 */
relativePath: string, 
/**
 * Operation type (upload/download)
 */
operation: QueueOperation, 
/**
 * Current status
 */
status: QueueStatus, 
/**
 * Priority (lower = higher priority)
 */
priority: number, 
/**
 * File size in bytes
 */
fileSize: bigint, 
/**
 * Error message if failed
 */
errorMessage: string | null, 
/**
 * Number of retry attempts
 */
retryCount: number, 
/**
 * When the entry was created
 */
createdAt: string, 
/**
 * When processing started
 */
startedAt: string | null, 
/**
 * When processing completed
 */
completedAt: string | null, };
