// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileState } from "./FileState";
import type { SyncConflict } from "./SyncConflict";

/**
 * Actions computed by the diff engine
 */
export type SyncActions = { toDownload: Array<FileState>, toUpload: Array<FileState>, 
/**
 * Relative paths of files to delete
 */
toDelete: Array<string>, toCreateDirectories: Array<string>, conflicts: Array<SyncConflict>, };
