// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileState } from "./FileState";

/**
 * A conflict detected during two-way sync
 */
export type SyncConflict = { relativePath: string, sourceState: FileState, targetState: FileState, };
