// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Statistics for a single table
 */
export type TableStats = { 
/**
 * Table name
 */
name: string, 
/**
 * Total number of rows
 */
totalRows: bigint, 
/**
 * Number of active (currently present) rows
 */
activeRows: bigint, 
/**
 * Number of delete-log entries targeting this table
 */
deleteLogRowCount: bigint, };
