// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which gate rejected the commit. Derived by matching the production
 * rejection strings, so a reworded message fails the spec loudly instead
 * of silently reclassifying an attack as "some other rejection".
 */
export type TestCommitGateOutcome = { "kind": "accepted" } | { "kind": "rejectedPhase1", reason: string, } | { "kind": "rejectedPop", reason: string, } | { "kind": "rejectedCommitBind", reason: string, } | { "kind": "rejectedCommitterCapability", reason: string, } | { "kind": "rejectedOther", reason: string, };
