// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Derived outcome of the propagation, if it ran.
 */
export type TestPropagationOutcome = { "kind": "notRun" } | { "kind": "appliedFullDelete" } | { "kind": "appliedRegisterOnly" } | { "kind": "notSharedInSpaceForgery" } | { "kind": "unshareRace" } | { "kind": "resurrectionSuppressed" } | { "kind": "unknown" };
