// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestUncheckedRemovalReport = { commitB64: string, 
/**
 * Valid bind-sig over `commit_b64`, signed with this vault's real
 * identity key. Pair it with a forged UCAN (Spec 3) or move it onto a
 * different commit to test replay (Spec 4).
 */
commitBindSigB64: string, committerDid: string, targetDid: string, };
