// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestPropagationOutcome } from "./TestPropagationOutcome";
import type { TestSharedSpaceRowSnapshot } from "./TestSharedSpaceRowSnapshot";

/**
 * Report returned by [`test_seed_shared_space_delete_log_entry`].
 */
export type TestSeedDeleteLogReport = { 
/**
 * Randomly generated UUID assigned to the synthesised delete-log entry.
 * Present in `haex_shared_space_deleted_rows` after this call returns
 * regardless of propagation outcome.
 */
deleteLogId: string, 
/**
 * Mirrors the `run_propagation` argument.
 */
propagated: boolean, 
/**
 * Derived from the before/after snapshot deltas.
 */
outcome: TestPropagationOutcome, before: TestSharedSpaceRowSnapshot, after: TestSharedSpaceRowSnapshot, };
