// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Snapshot of the observable state around a `(space_id, table_name, row)`
 * tuple. Captured before and after the seeded propagation runs so the caller
 * can derive what happened without instrumenting the propagation code path.
 */
export type TestSharedSpaceRowSnapshot = { 
/**
 * Row currently registered for `(table, row_pks, space_id)` in
 * `haex_shared_space_sync`.
 */
targetSpaceRegistered: boolean, 
/**
 * Row registered for `(table, row_pks)` in ANY space.
 */
anySpaceRegistered: boolean, 
/**
 * Business row present in `table_name` for `row_pks`.
 */
businessRowExists: boolean, };
