// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TestCommitGateOutcome } from "./TestCommitGateOutcome";

/**
 * Result of feeding one commit into the real receive path.
 */
export type TestCommitGateReport = { outcome: TestCommitGateOutcome, 
/**
 * MLS epoch before / after. Equal on every rejection — the assertion
 * that the gate really is fail-closed on the group state, not just on
 * the returned error.
 */
epochBefore: bigint, epochAfter: bigint, 
/**
 * Whether `resolve_presented_committer_capability` produced a
 * capability at all, and its audience/level when it did. Lets a spec
 * tell "UCAN failed to verify" apart from "UCAN verified but the gate
 * still said no" — indistinguishable in the production error string.
 */
resolvedAudienceDid: string | null, resolvedLevel: string | null, };
