// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tombstone entry for display
 */
export type TombstoneEntry = { 
/**
 * Table name
 */
tableName: string, 
/**
 * Primary key value(s) as JSON string
 */
primaryKey: string, 
/**
 * When the entry was deleted (HLC timestamp)
 */
deletedAt: string, };
