// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transfer session state
 */
export type TransferState = "pending" | "inprogress" | "completed" | "rejected" | "cancelled" | "failed";
