// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transfer progress update (for events)
 */
export type TransferProgress = { 
/**
 * Session ID
 */
sessionId: string, 
/**
 * File ID
 */
fileId: string, 
/**
 * File name
 */
fileName: string, 
/**
 * Bytes transferred
 */
bytesTransferred: bigint, 
/**
 * Total bytes
 */
totalBytes: bigint, 
/**
 * Transfer speed in bytes/sec
 */
speed: bigint, };
