// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update a storage backend
 */
export type UpdateStorageBackendRequest = { 
/**
 * Backend ID to update
 */
backendId: string, 
/**
 * New display name (optional)
 */
name: string | null, 
/**
 * New configuration (optional) - only provided fields are updated
 * If credentials are omitted, existing credentials are preserved
 */
config: Record<string, unknown> | undefined, };
