// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictStrategy } from "./ConflictStrategy";
import type { SyncDirection } from "./SyncDirection";

export type UpdateSyncRuleRequest = { ruleId: string, backendIds: Array<string> | null, direction: SyncDirection | null, enabled: boolean | null, 
/**
 * Gitignore-like patterns for files/folders to exclude from sync
 */
ignorePatterns: Array<string> | null, 
/**
 * Default conflict resolution strategy
 */
conflictStrategy: ConflictStrategy | null, };
