// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update extension limits
 */
export type UpdateExtensionLimitsRequest = { extensionId: string, 
/**
 * Query timeout in milliseconds (optional, keeps current value if not provided)
 */
queryTimeoutMs: bigint | null, 
/**
 * Maximum result rows per query (optional)
 */
maxResultRows: bigint | null, 
/**
 * Maximum concurrent queries (optional)
 */
maxConcurrentQueries: bigint | null, 
/**
 * Maximum query SQL size in bytes (optional)
 */
maxQuerySizeBytes: bigint | null, };
