// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request a streaming upload from a local file.
 *
 * Mirrors [`DownloadToPathRequest`]. The backend reads `source_path` in
 * chunks and pushes to the configured remote; progress + cancellation
 * flow through `AppState.transfer_tokens` keyed by `transfer_id`, same
 * as the download path.
 */
export type UploadFromPathRequest = { 
/**
 * Backend ID to upload to
 */
backendId: string, 
/**
 * Object key (path in the bucket)
 */
key: string, 
/**
 * Absolute path on disk of the file to upload.
 */
sourcePath: string, 
/**
 * Caller-generated transfer id, used to route progress events and
 * cancellation requests.
 */
transferId: string, };
